spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://laweasy.cegkrgywkavi.ap-northeast-2.rds.amazonaws.com:3306/laweasy?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: Easy0703!

  jpa:
    hibernate:
      naming:
        # Entity Table 대소문자 구분
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # Initial Data config
    defer-datasource-initialization: true

